### ISSUE TITLE
How to show online status in Toolbar component as well?

### ISSUE THREAD

**Issue by crazycodewriter** [uzochukwueddie/chatapp-frontend#3]
Hey @uzochukwueddie  in the tutorial you use output and event emitter for displaying online status in other components while the main code is written in Tool-bar component. How can I display online status in tool-bar itself?

```
ngOnInit() {
    this.socket.emit('online', { room: 'global', user: this.user.username });
    this.socket.on('refreshPage', () => {
      this.GetUserData(this.name);
    });
  ...
  ...
ngAfterViewInit() {
    this.socket.on('usersOnline', data => {
      console.log(data);
    });
  }
```

should I copy and paste this from other components?

```
CheckIfOnline(name) {
    const result = _.indexOf(this.onlineusers, name);
    if (result > -1) {
      return true;
    } else {
      return false;
    }
  }
```

If yes then how will it work with above ngAfterViewInit?
I want to add this p in toolbar:
`<p class="" *ngIf="CheckIfOnline(user.username)">online</p>`

**Comment by uzochukwueddie** [comment]
The online users are inside the data array in  ngAfterViewInit. That is
what is emitted to other components using EventEmitters.
You can create a variable and set it equal to the data values (All inside
your toolbar component).
Then you can use the CheckIfOnline method and the p tag inside wherever you
want to in your toolbar component.
The @Output event emitter is for other components to get the online users

**Comment by crazycodewriter** [comment]
@uzochukwueddie that's the most confusing part. Let's say a variable is **onlineUsers**. How should it be used instead of that `console.log(data)` and work with:

```
CheckIfOnline(name) {
    const result = _.indexOf(this.onlineusers, name);
    if (result > -1) {
      return true;
    } else {
      return false;
    }
  }
```

inside toolbar.
